package cse.project.team;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Model classUnderTest = new Model();
        classUnderTest.addData("bacon", "stuff");
        assertEquals(classUnderTest.getDetails("bacon"), "stuff");
    }
}